INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('factoid', 'Interesting Quote', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('factoid', 'How You Can Help', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('factoid', 'Editing', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('status', 'Height (in feet)', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('status', 'Diameter (in inches)', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Needs Watering', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Needs Pruning', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Should Be Removed', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Pest or Disease present', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Guard Should be Removed', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Stakes and Ties Should be Removed', '6', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Construction Work in the Area', '7', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Touching Wires', '8', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Blocking Signs or Traffic Signals', '9', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('alert', 'Improperly Pruned or Topped', '10', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('action', 'Watered', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('action', 'Pruned', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('action', 'Fruit or Nuts Harvested', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('action', 'Removed', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('action', 'Inspected', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('local', 'Landmark Tree', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('local', 'Local Carbon Fund', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('local', 'Fruit Gleaning Project', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('local', 'Historically Significant Tree', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('factoid', 'General', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('sidewalk_damage', 'Minor or No Damage', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('sidewalk_damage', 'Raised More Than 3/4 Inch', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Dead', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Critical', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Fair', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Good', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Very Good', '6', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Excellent', '7', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('bool_set', 'Yes', 'True', 'bool');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('bool_set', 'No', 'False', 'bool');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('canopy_condition', 'Small Gaps (up to 25% missing)', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('canopy_condition', 'Full - No Gaps', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('canopy_condition', 'Moderate Gaps (up to 50% missing)', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('canopy_condition', 'Large Gaps (up to 75% missing)', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('canopy_condition', 'Little or None (up to 100% missing)', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Other', '7', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Natural Area', '8', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Well or Pit', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Median', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Tree Lawn', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Island', '4', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Planter', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Open', '6', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('powerline_conflict_potential', 'Yes', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('powerline_conflict_potential', 'No', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('steward_name', 'City of Asheville', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('steward_name', 'Private Tree', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('tree_owner', 'City of Asheville', '1', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('tree_owner', 'Asheville Greenworks', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('tree_owner', 'Private', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('steward_name', 'Asheville Greenworks', '2', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('factoid', 'Interesting Fact', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('local', 'Asheville Greenworks Treasure Tree', '5', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('local', 'Bee Favorite', '6', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('tree_owner', 'Unknown Owner', '0', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('steward_name', 'Unknown Steward', '0', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('canopy_condition', 'Unknown Canopy Condition', '6', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Unknown Condition', '8', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('plot_type', 'Unknown Plot Type', '9', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('condition', 'Poor', '3', 'int');
INSERT INTO "public"."treemap_choices" ("field", "value", "key", "key_type") VALUES ('powerline_conflict_potential', 'Unknown Powerline', '3', 'int');
COMMIT;
